### ISSUE TITLE
no vendor folder that contains all the jquery and css

### ISSUE THREAD

**Issue by ahmadzt** [erhankilic/AdminLteWpTheme#1]
there should be vendor/AdminLTE/ folder. Am i making mistakes or the files are actually missing?

**Comment by erhankilic** [comment]
You need to install it with bower (I wrote at readme) or you could manually download AdminLTE and move under the vendor folder.

**Comment by ahmadzt** [comment]
my bad. thanks for the fast reply.

**Comment by erhankilic** [comment]
You're welcome.
