### ISSUE TITLE
Theme Not Loading In WP

### ISSUE THREAD

**Issue by MCgamin1738** [erhankilic/AdminLteWpTheme#3]
Hi,

I Downloaded Your Repo, And Downloaded AdminLTE 3.0.4, I Put It In vendors/AdminLTE, I Put It All In A Zip File, Uploaded It To WP And Then Went To The Live Preview, And I Had An Endless Loading Screen, What Am I Doing Wrong?

Thanks In Advance

**Comment by erhankilic** [comment]
@MCgamin1738 First of all you need to download Admin LTE version 2, not 3. After that what do you see when you open the browser's javscript console? are there any errors?

**Comment by MCgamin1738** [comment]
I Just Changed To Version 2.4.18, It Is Still Not Working, It Says This In The Console: 
![image](https://user-images.githubusercontent.com/61501441/78280056-643f0680-7510-11ea-9f4f-71253a536e54.png)

**Comment by erhankilic** [comment]
It seems it can't load the js files. Please check them all if they're exist or not.

**Comment by MCgamin1738** [comment]
They Don't Exist, Where Should I Get Them?

**Comment by MCgamin1738** [comment]
I Got It Working, I Had To Go To AdminLTE 2.3

Thanks
